# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHmjlVwnTgOhBxvpxKA5-3a9V24HEMUn

Part 1
"""

decimal = input("Input decimal integer larger than 20 here: ");

if int(decimal) > 20:

    binary = bin(int(decimal))
    hexadecimal = hex(int(decimal))
    print(decimal)

    print(binary)
    # check if the binary number is the same as the decimal number
    if int(binary, 2) == int(decimal):
      print('True')
    else:
      print('False')

    print(hexadecimal)
    # check if the hexadecimal number is the same as the decimal number
    if int(hexadecimal, 16) == int(decimal):
      print('True')
    else:
      print('False')

else:

    print('Input Invalid')

"""Part 2"""

# Define the variables
num_1= 10
num_2 = 11.0
course_code = "cs104"
course_name = "Intro CS Using Python"
my_name= "Connor Capolupo"

# Print basic variables
print(num_1)
print(num_2)
print(course_name)

# Define and print num_4
num_4 = num_1 * num_2
print(num_4)

# Define and print num_5
num_5 = num_2 / num_1
print(num_5)

# Print the integer and remainder of num_2 / num_1
print(1)
print(0.1)

# Print the final output
print(my_name + " is taking " + course_code + ": " + course_name)
