# -*- coding: utf-8 -*-
"""Lab2.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5iEMdsegqeq7j___7qqchcqcvG7vR9T
"""

# General Variables
names = []
grades = []
number = int(input("Enter Number of Students: "))
sum = 0

for i in range(number):
  # Takes Inputs for Names and Grades
  names.append(input("Enter Name Here: "))
  grades.append(input("Enter Grade Here: "))

with open("grade_report.txt", "w") as f:
  for i in range(number):
    # Finds the Spacing for the Name
    space = (10 - len(names[i])) * " "
    f.write(f"{names[i]}: {space} {grades[i]}\n")
    sum += float(grades[i])
  # Writes the Average Grade to the File
  f.write(f"Average Grade: {float(sum / number):.2f}")
  average = float(sum / number)
  # Converts the Grade Number into a Letter
  if average >= 90:
    letter_average = "A"
  elif average >= 80:
    letter_average = "B"
  elif average >= 70:
    letter_average = "C"
  elif average >= 60:
    letter_average = "D"
  else:
    letter_average = "F"
  f.write(f"\nAverage Letter Grade: {letter_average}")

print("File grade_report.txt is made")