# -*- coding: utf-8 -*-
"""Lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Fm12G5KZee3Sc0Jn0Ql0EHc3dLdX4OV
"""

# Variable definitions
msg = input("Enter message here: ")
cipher = round(float(input("Enter Cipher Shift Here: ")))
encoded_message = []
check_max = 126
check_min = 32
check = range(check_min, check_max + 1)

# Put all letters list
for i in msg:
  if ord(i) + cipher in check:
    encoded_message.append(chr(ord(i) + cipher))
  elif ord(i) + cipher > check_max:
    encoded_message.append(chr((check_min + (ord(i) + cipher)) - check_max + 1))
  elif ord(i) + cipher < check_min:
    encoded_message.append(chr(check_max - (check_min - 1 -(ord(i) + cipher))))

# Print encoded message
message = "".join(encoded_message)
print(f"Encoded message:", message)

# Reset variables
msg = message
encoded_message = []

# Invert the cipher
cipher = cipher * -1

# Run the caesar cipher code again
for i in msg:
  if ord(i) + cipher in check:
    encoded_message.append(chr(ord(i) + cipher))
  elif ord(i) + cipher > check_max:
    encoded_message.append(chr((check_min + (ord(i) + cipher)) - check_max + 1))
  elif ord(i) + cipher < check_min:
    encoded_message.append(chr(check_max - (check_min - 1 -(ord(i) + cipher))))

# Print decoded message
message = "".join(encoded_message)
print(f"Decoded message:", message)